blueprint:
  name: "HA Video Vision - Camera Alert"
  description: >
    When person is detected, record video, run AI analysis,
    and send mobile notifications with snapshot. Optionally identify
    known faces using the Facial Recognition add-on.
    Works with iOS and Android via Nabu Casa.
  domain: automation
  author: "HA Video Vision Integration"
  source_url: "https://github.com/LosCV29/ha-video-vision/blob/main/custom_components/ha_video_vision/blueprints/automation/camera_alert.yaml"

  input:
    person_sensor:
      name: "Person Sensor"
      description: "Binary sensor that triggers on person detection"
      selector:
        entity:
          domain: binary_sensor

    camera_name:
      name: "Camera Name"
      description: "Camera name as configured in HA Video Vision (e.g., 'porch', 'driveway')"
      selector:
        text:

    notify_devices:
      name: "Notify Devices"
      description: "Select mobile devices to notify (iOS and Android)"
      default: []
      selector:
        device:
          multiple: true
          filter:
            integration: mobile_app

    notify_start:
      name: "Notify After"
      description: "Only send notifications after this time (leave default for always)"
      default: "00:00:00"
      selector:
        time:

    notify_end:
      name: "Notify Before"
      description: "Only send notifications before this time (leave default for always)"
      default: "23:59:59"
      selector:
        time:

    custom_prompt:
      name: "Custom Prompt (Optional)"
      description: "Override the AI prompt. Leave empty for default factual description."
      default: ""
      selector:
        text:
          multiline: true

    cooldown:
      name: "Cooldown (minutes)"
      description: "Wait time between notifications for this camera"
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: "min"
      default: 2

    notification_title:
      name: "Notification Title"
      description: "Custom title for notifications (e.g., 'Front Door', 'Backyard'). Leave empty to use camera name."
      default: ""
      selector:
        text:

    tap_navigate:
      name: "Tap Navigate"
      description: "Dashboard to open when notification is tapped"
      default: "/lovelace/0"
      selector:
        text:

    critical_alert:
      name: "Critical Alert (iOS)"
      description: "Bypass Do Not Disturb on iOS devices"
      default: false
      selector:
        boolean:

    capture_delay:
      name: "Capture Delay (seconds)"
      description: "Wait time before capturing. Set to 0 for INSTANT recording when person detected. Increase for cloud cameras (Ring, Nest) that need time to process new video (use 3-5s for cloud cameras)."
      default: 0
      selector:
        number:
          min: 0
          max: 10
          step: 1
          unit_of_measurement: "s"

    frame_position:
      name: "Notification Frame Position (%)"
      description: "Which frame from the video to use for the notification image. 0% = first frame, 50% = middle, 100% = last frame."
      default: 50
      selector:
        number:
          min: 0
          max: 100
          step: 10
          unit_of_measurement: "%"

    # Facial Recognition
    facial_recognition_enabled:
      name: "Enable Facial Recognition"
      description: "Identify known faces using the Facial Recognition add-on. Configure the server URL in the integration settings."
      default: false
      selector:
        boolean:

    facial_recognition_frame_position:
      name: "Facial Recognition Frame Position (%)"
      description: "Which frame to use for facial recognition. SEPARATE from notification image. Use 50% (middle) or higher to capture faces after people have walked closer to the camera."
      default: 50
      selector:
        number:
          min: 0
          max: 100
          step: 10
          unit_of_measurement: "%"

    # Timeline
    save_to_timeline:
      name: "Save to Timeline"
      description: "Save each analysis to the Timeline calendar. View history in the Calendar panel or dashboard."
      default: true
      selector:
        boolean:

mode: single
max_exceeded: silent

variables:
  notify_devices: !input notify_devices
  critical: !input critical_alert
  tap_nav: !input tap_navigate
  camera_input: !input camera_name
  user_prompt: !input custom_prompt
  custom_title: !input notification_title
  time_start: !input notify_start
  time_end: !input notify_end
  delay_seconds: !input capture_delay
  frame_pos: !input frame_position
  face_rec_enabled: !input facial_recognition_enabled
  face_rec_frame_pos: !input facial_recognition_frame_position
  timeline_enabled: !input save_to_timeline
  # Default prompt - reports ALL people/vehicles whether moving or stationary
  default_prompt: "Describe any people, vehicles, or notable activity visible. Report ALL people and vehicles, whether moving or stationary. For people, describe their appearance and actions. Ignore static background objects like parked cars and structures. If no people, vehicles, or notable activity are present, respond: 'No activity observed.' 2-3 sentences max."
  # Build service names from device IDs
  device_services: >
    {% set ns = namespace(services=[]) %}
    {% for device_id in notify_devices %}
      {% set device_name = device_attr(device_id, "name") %}
      {% set service_name = "mobile_app_" + device_name | slugify %}
      {% set ns.services = ns.services + [service_name] %}
    {% endfor %}
    {{ ns.services }}

trigger:
  - platform: state
    entity_id: !input person_sensor
    to: "on"

condition:
  # Check if current time is within notification window
  - condition: time
    after: !input notify_start
    before: !input notify_end

action:
  # Optional delay for cloud cameras - skip if 0 for instant recording
  - if:
      - condition: template
        value_template: "{{ delay_seconds > 0 }}"
    then:
      - delay:
          seconds: "{{ delay_seconds }}"

  # Analyze camera with prompt - VIDEO ONLY analysis
  # Frame position determines which video frame is used for notification image
  # Facial recognition uses a separate frame position for better face capture
  - service: ha_video_vision.analyze_camera
    data:
      camera: !input camera_name
      # Duration omitted - uses integration's configured video_duration for consistent recording length
      user_query: "{{ user_prompt if user_prompt else default_prompt }}"
      facial_recognition: "{{ face_rec_enabled }}"
      facial_recognition_frame_position: "{{ face_rec_frame_pos }}"
      remember: "{{ timeline_enabled }}"
      frame_position: "{{ frame_pos }}"
    response_variable: result

  # Send notifications if successful
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ result.success == true }}"
        sequence:
          - variables:
              # Use custom title if provided, otherwise use camera friendly name
              notification_title: "{{ custom_title if custom_title else result.friendly_name }}"
              # Include facial recognition results in message if available
              notification_message: >
                {% set desc = result.description if result.description else 'Motion detected on camera' %}
                {% set face_rec = result.get('face_recognition', {}) %}
                {% if face_rec.get('success') and face_rec.get('summary') and face_rec.get('summary') != 'No known faces' %}
                  {{ face_rec.summary }} - {{ desc }}
                {% else %}
                  {{ desc }}
                {% endif %}

          # Send to all devices
          - repeat:
              for_each: "{{ device_services }}"
              sequence:
                - service: "notify.{{ repeat.item }}"
                  data:
                    title: "{{ notification_title }}"
                    message: "{{ notification_message }}"
                    data:
                      # Image - works for both platforms
                      image: "{{ result.snapshot_url }}"
                      # Tap actions
                      url: "{{ tap_nav }}"
                      clickAction: "{{ tap_nav }}"
                      # Grouping - no tag means notifications STACK instead of overwrite
                      group: "ha_video_vision"
                      # Priority
                      ttl: 0
                      priority: high
                      # Android
                      channel: "ha_video_vision"
                      sticky: true
                      # iOS
                      attachment:
                        url: "{{ result.snapshot_url }}"
                        content_type: JPEG
                      push:
                        interruption-level: "{{ 'critical' if critical else 'time-sensitive' }}"
                        sound:
                          name: default
                          critical: "{{ 1 if critical else 0 }}"
                          volume: "{{ 1.0 if critical else 0.5 }}"
    default:
      - service: system_log.write
        data:
          message: "HA Video Vision failed for {{ camera_input }}: {{ result.error }}"
          level: warning

  # Cooldown
  - delay:
      minutes: !input cooldown
